name: 'aur auto update'
inputs:
  packages:
    description: 'packages to be updated'
    required: true
runs:
  using: "composite"
  steps:
    - run: sudo pacman -Suy --noconfirm git openssh pacman-contrib rust sudo
      shell: bash
    - run: |
        useradd -m -U aur
        echo "aur ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/user
      shell: bash
    - run: su aur --command "git clone https://github.com/LuckyTurtleDev/aur-auto-update-ci.git"
      working-directory: /home/aur
      shell: bash
    - run: su aur --command "mkdir /home/aur/.ssh && cp /home/aur/aur-auto-update-ci/aur_known_hosts /home/aur/.ssh/known_hosts"
      shell: bash
    - uses: actions/cache@v3
      with:
        path: |
          /home/aur/.cargo/registry/index/
          /home/aur/.cargo/registry/cache/
          /home/aur/.cargo/git/db/
          /home/aur/aur-auto-update-ci/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('/home/aur/aur-auto-update-ci/Cargo.lock') }}
    - run: chown -R aur:aur /home/aur #fix cache permissions
      shell: bash
    - run: su aur --command "cargo run --release -- ${{ inputs.packages }}"
      working-directory: /home/aur/aur-auto-update-ci
      shell: bash
