name: update

on:
  push:
  repository_dispatch:

jobs:
  update_packages:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
      - uses: LuckyTurtleDev/aur-auto-update-ci@main
        with:
          packages: commander-wars
          ssh_key: ${{ secrets.SSH_KEY_ED25519 }}
          git_user_name: LuckyTurtleCI
